### PR TITLE
Functor to provide easily the same interface as Stdlib.Random

### PR DESCRIPTION
**Pull request by Niols**
Is it looking fine?

Before merging, I would like to:

- [x] find a better name for this module. Ideas?
- [x] use the `Basic` functor on `Stdlib.Random.bits` and run tests to check that we are indeed deriving other functions in the same way as stdlib does.
- [x] use the functor on xoshiro256++ and compare benchmarks.

Comments?

### CODE REVIEW

**Comment by Niols** [comment]
Used the functor to add benchmarks on float and on int64.

Generating float:
```
┌───────────────────────────────────┬──────────┬─────────┬────────────┐
│ Name                              │ Time/Run │ mWd/Run │ Percentage │
├───────────────────────────────────┼──────────┼─────────┼────────────┤
│ Random.float                      │  18.78ns │   4.00w │     44.31% │
│ X256pp.Int64.float                │  42.39ns │  23.00w │    100.00% │
│ X256pp.C.float                    │  12.40ns │   2.00w │     29.26% │
│ RandomFunctor(Random).float       │  20.79ns │   4.00w │     49.04% │
│ RandomFunctor(X256pp.Int).float   │  14.46ns │   4.00w │     34.10% │
│ RandomFunctor(X256pp.Int64).float │  14.40ns │   4.00w │     33.97% │
│ RandomFunctor(X256pp.C).float     │  15.92ns │   4.00w │     37.56% │
└───────────────────────────────────┴──────────┴─────────┴────────────┘
```

And generating int64:
```
┌───────────────────────────────────┬──────────┬─────────┬────────────┐
│ Name                              │ Time/Run │ mWd/Run │ Percentage │
├───────────────────────────────────┼──────────┼─────────┼────────────┤
│ Random.int64                      │  36.06ns │   3.00w │     93.58% │
│ RandomFunctor(Random).int64       │  38.53ns │   3.00w │    100.00% │
│ RandomFunctor(X256pp.Int).int64   │  19.49ns │   3.00w │     50.58% │
│ RandomFunctor(X256pp.Int64).int64 │  20.08ns │   3.00w │     52.11% │
│ RandomFunctor(X256pp.C).int64     │  28.31ns │   3.00w │     73.46% │
└───────────────────────────────────┴──────────┴─────────┴────────────┘
```

---

Interestingly:

- `Random` seems faster than `RandomFunctor(Random)`. This might be because of how the basic functor is generated. I derived it from the full functor to avoid code duplication. But this might add some delay, I'll look into it. Or maybe it's only that there is one extra indirection in the functor.

- `X256pp.Int64.float` proves to be extremely slow. I guess it comes from how `float` is derived from `bits`. The way the standard lib does it seems much more efficient considering that `RandomFunctor(X256pp.Int64).float` is much faster.

- `X256pp.C` is indeed slower than both `X256pp.Int` and `X256pp.Int64`.

- Despite being slower than `X256pp.Int` on `bits`, `X256pp.Int64` catches up on other endpoints and proves to be actually a little faster. Compiler magic?

**Comment by Niols** [comment]
I tried getting rid of as many indirections as I could in the functor. There is definitely an impact. It is however unclear to see what had which impact. More involved benchmarking would be required. I will try to do that later.

**Comment by Kerl13** [comment]
Neat and well-documented, thanks!

> find a better name for this module. Ideas?

You suggested `MakeRandom.{Full|Basic}` on signal. I'm okay with this name.

> use the `Basic` functor on `Stdlib.Random.bits` and run tests to check that we are indeed deriving other functions in the same way as stdlib does.

Did you have time to do this? I'm actually pretty confident the functor is "correct" in that sense tbh.

> use the functor on xoshiro256++ and compare benchmarks.

You ran a lot of benchmarks already showing that the functor has little overhead, if any. I think this version is more than good enough for now and does not require more benchmarking.
If you used some scripts to run the benchmarks it would be nice to add them by the way.

**Review by Kerl13 — APPROVED** [review]
Looks good to me

**Comment by Niols** [comment]
> > find a better name for this module. Ideas?
> 
> You suggested `MakeRandom.{Full|Basic}` on signal. I'm okay with this name.

Done. I also moved the whole thing to its own subdir `make-random` and sublibrary.

> > use the `Basic` functor on `Stdlib.Random.bits` and run tests to check that we are indeed deriving other functions in the same way as stdlib does.
> 
> Did you have time to do this? I'm actually pretty confident the functor is "correct" in that sense tbh.

I just added this. There is a test file in `make-random/test.ml` that compares runs of `Random` and `MakeRandom.Basic(Random)` on the same seed. Pretty simple, but probably enough. It is also registered as a test in Dune.

> > use the functor on xoshiro256++ and compare benchmarks.
> 
> You ran a lot of benchmarks already showing that the functor has little overhead, if any. I think this version is more than good enough for now and does not require more benchmarking.
> If you used some scripts to run the benchmarks it would be nice to add them by the way.

I moved the benchmarks specific to the functor overhead to `make-random/bench.ml`. It only compares `Random` and `MakeRandom.Basic(Random)`. If them with `dune exec make-random/bench.exe time cycles percentage`, it shows an overhead of less than 10% for all functions except a bit more for `float` as it calls the `bits` function twice.

Anything else we would want to do for this PR? Maybe add a README to document all this?

**Comment by Kerl13** [comment]
> Anything else we would want to do for this PR? Maybe add a README to document all this?

Yep why not :+1:

**Comment by Niols** [comment]
I hoped you wouldn't say that.

**Comment by Kerl13** [comment]
> I hoped you wouldn't say that.

Ahah just don't then ^^ that's fine

**Comment by Kerl13** [comment]
I would just indicate :
- which command to run in order to execute the benchmarks
- to refer to the `.mli` file for documentation

**Pull request merged**
